# Generated by Django 3.1.6 on 2021-02-18 14:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_data',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('proband', models.BooleanField(blank=True, choices=[(True, 'Y'), (False, 'N')], null=True)),
                ('affected_relatives', models.BooleanField(blank=True, choices=[(True, 'Y'), (False, 'N')], null=True)),
                ('stage', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], null=True)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variant_data',
            fields=[
                ('variant_id', models.AutoField(primary_key=True, serialize=False)),
                ('sequencer', models.CharField(choices=[('HiSeq', 'HiSeq'), ('MiSeq', 'MiSeq')], max_length=20, null=True)),
                ('gene', models.CharField(default='BRCA1', max_length=10, null=True)),
                ('chrm', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('X', 'X'), ('Y', 'Y')], default='17', max_length=2, null=True)),
                ('variant_cdna', models.CharField(max_length=200, null=True)),
                ('variant_protein', models.CharField(max_length=200, null=True)),
                ('variant_genome', models.CharField(max_length=200, null=True)),
                ('code_pathogenicity', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
                ('codes_evidence', models.CharField(blank=True, max_length=200)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DB.patient_data')),
            ],
        ),
    ]
