# Generated by Django 3.1.6 on 2021-02-17 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testvariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('proband', models.BooleanField(choices=[(True, 'Y'), (False, 'N')], null=True)),
                ('Description', models.CharField(max_length=500, null=True)),
                ('sequencer', models.CharField(choices=[('HiSeq', 'HiSeq'), ('MiSeq', 'MiSeq')], max_length=20, null=True)),
                ('gene', models.CharField(max_length=10, null=True)),
                ('variant_cdna', models.CharField(max_length=200, null=True)),
                ('variant_protein', models.CharField(max_length=200, null=True)),
                ('variant_genome', models.CharField(max_length=200, null=True)),
                ('code_pathogenicity', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
                ('codes_evidence', models.CharField(blank=True, max_length=200)),
                ('uploaded_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
