# Generated by Django 3.1.6 on 2021-02-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testvariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('proband', models.BooleanField()),
                ('uploaded_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
