# Generated by Django 3.1.6 on 2021-02-18 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant_data',
            name='code_pathogenicity',
        ),
        migrations.RemoveField(
            model_name='variant_data',
            name='codes_evidence',
        ),
        migrations.RemoveField(
            model_name='variant_data',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='variant_data',
            name='sequencer',
        ),
        migrations.AlterField(
            model_name='patient_data',
            name='stage',
            field=models.CharField(choices=[('Not cancer', 'Not cancer'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Test_data',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('sequencer', models.CharField(choices=[('HiSeq', 'HiSeq'), ('MiSeq', 'MiSeq')], max_length=20, null=True)),
                ('uploaded_time', models.DateTimeField(blank=True, null=True)),
                ('patient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DB.patient_data')),
                ('variant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DB.variant_data')),
            ],
        ),
        migrations.CreateModel(
            name='Interpretation_data',
            fields=[
                ('Interpretation_id', models.AutoField(primary_key=True, serialize=False)),
                ('code_pathogenicity', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
                ('codes_evidence', models.CharField(blank=True, max_length=200)),
                ('uploaded_time', models.DateTimeField(blank=True, null=True)),
                ('variant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DB.variant_data')),
            ],
        ),
    ]
