# Generated by Django 3.1.6 on 2021-02-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testvariant',
            name='code_pathogenicity',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1),
        ),
        migrations.AddField(
            model_name='testvariant',
            name='codes_evidence',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='testvariant',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='testvariant',
            name='gene',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='testvariant',
            name='sequencer',
            field=models.CharField(choices=[('HiSeq', 'HiSeq'), ('MiSeq', 'MiSeq')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='testvariant',
            name='variant_cdna',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testvariant',
            name='variant_genome',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testvariant',
            name='variant_protein',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='testvariant',
            name='proband',
            field=models.BooleanField(choices=[(True, 'Y'), (False, 'N')], null=True),
        ),
    ]
